import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from '@/redux/provider'
import { ProviderAuth } from '@/components/auth/ProviderAuth'
import ProviderQuery from '@/util/provider'
// import ProviderQuery from ''

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ProviderAuth>
            <ProviderQuery>
              {children}
            </ProviderQuery>
          </ProviderAuth>
        </Providers>
      </body>
    </html>
  )
}
